### PR TITLE
add decorators

### PR DESCRIPTION
**Pull request by smasalovich**
add decorators

### CODE REVIEW

**Comment by gruntoff** [comment]
You didn't use your function as a decorator. Please pay attention to the task example.
Also it would be nice if you calculated execution time by yourself, not used `timeit()` function.

**Comment by smasalovich** [comment]
don't sure that i understood, what did you mean in 'not used timeit() function', i can use time. or datetime probably, and doing simple math with it, are any other ways for calculate it without adding modules? in example used time,   but don't see many difference between ways of realizations

**Comment by gruntoff** [comment]
`time`, `datetime` are okay. 
Pay attention that decorator is used like this:
```
@measure_elapsed_time
    def my_func():
        pass
```
Also please include example code in your solution in order to check if your code behaves as expected.

**Comment by smasalovich** [comment]
hope it is correct now

**Pull request merged**
